MVCProjeKampi/MVCProjeKampi/Controllers/HeadingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using DataAccessLayer;
using DataAccessLayer.EntityFramework;
using EntityLayer;

namespace MVCProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());

        Context c = new Context();

        public ActionResult Index()
        {
            var headingValues = hm.GetList();
            return View(headingValues);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }
                ).ToList();
            ViewBag.vlc = valueCategory;

            List<SelectListItem> valueWriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName+" "+x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }
                ).ToList();
            ViewBag.vlw = valueWriter;

            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(heading);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                    select new SelectListItem
                    {
                        Text = x.CategoryName,
                        Value = x.CategoryID.ToString()
                    }
                ).ToList();
            ViewBag.vlc = valueCategory;
            var headingValue = hm.GetByID(id);
            return View(headingValue); 
        }

        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            hm.HeadingUpdate(heading);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id)
        {
            var HeadingValue = hm.GetByID(id);

            if (HeadingValue.HeadingStatus == true)
            {
                HeadingValue.HeadingStatus = false;
            }
            else
            {
                HeadingValue.HeadingStatus = true;
            }

            hm.HeadingDelete(HeadingValue);
            return RedirectToAction("Index");
        }
    }
}

MVCProjeKampi/MVCProjeKampi/Views/Heading/AddHeading.cshtml
@model EntityLayer.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Ekleme Sayfası</h2>

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">

        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x=>x.CategoryID,(List<SelectListItem>)ViewBag.vlc,new{@class="form-control"})
        @Html.ValidationMessageFor(x => x.CategoryID)
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x=>x.WriterID,(List<SelectListItem>)ViewBag.vlw,new{@class="form-control"})
        @Html.ValidationMessageFor(x=>x.WriterID)
        <br/>
        <button class="btn btn-primary" type="submit">Ekle</button>

    </div>
}

MVCProjeKampi/MVCProjeKampi/Views/Heading/EditHeading.cshtml
@model EntityLayer.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Başlık ID")
    @Html.TextBoxFor(x => x.HeadingID, new { @class = "form-control" })
    <br />
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Başlık Zamanı")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
    <br />
   
  
    @Html.Label("Kategori Adı")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success" type="submit">Güncelle</button>
</div>
}

MVCProjeKampi/MVCProjeKampi/Views/Heading/Index.cshtml
@using EntityLayer
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    string color = "";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    
        <!-- Navbar -->
        
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        

        <!-- Content Wrapper. Contains page content -->
       
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>Başlıklar</h1>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">

                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Başlık İşlemleri</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <table class="table table-striped projects">
                            <thead>
                                <tr>
                                    <th style="width: 1%">
                                        #
                                    </th>
                                    <th style="width: 20%">
                                        Başlık Adı
                                    </th>
                                    <th style="width: 15%">
                                        Oluşturan Yazar
                                    </th>
                                    <th style="width: 10%">
                                        Durum
                                    </th>
                                    <th style="width: 8%" class="text-center">
                                        Kategori
                                    </th>
                                    <th style="width: 20%">
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach (var item in Model)
                            {
                                switch (item.CategoryID)
                                        {
                                            case 1:
                                                color = "badge badge-success";
                                                break;
                                            case 2:
                                                color = "badge badge-danger";
                                                break;
                                            case 3:
                                                color = "badge badge-primary";
                                                break;
                                            case 4:
                                                color = "badge badge-dark";
                                                break;
                                            case 5:
                                                color = "badge badge-secondary";
                                                break;
                                            case 6:
                                                color = "badge badge-info";
                                                break;
                                        }
                                <tr>
                                    <td>
                                        @item.HeadingID
                                    </td>
                                    <td>
                                        <a>
                                            @item.HeadingName
                                        </a>
                                        <br/>
                                        <small>
                                           @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))    @* @item.HeadingDate.ToShortDateString() *@
                                        </small>
                                    </td>
                                    <td>
                                        <ul class="list-inline">
                                            <li class="list-inline-item">
                                                <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                            </li>
                                        </ul>
                                    </td>
                                    <td>
                                        @if (item.HeadingStatus == true)
                                        {
                                            <badge class="badge badge-primary">Aktif</badge>
                                        }
                                        else
                                        {
                                            <badge class="badge badge-danger">Pasif</badge>
                                        }
                                    </td>
                                    <td class="project-state">
                                        <span class="@color">@item.Category.CategoryName</span>
                                    </td>
                                    <td class="project-actions text-right">
                                        <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                            <i class="fas fa-folder">
                                            </i>
                                            İçerik
                                        </a>
                                        <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                            <i class="fas fa-pencil-alt">
                                            </i>
                                            Düzenle
                                        </a>
                                        @if (item.HeadingStatus == true)
                                        {
                                            <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                                <i class="fas fa-trash">
                                                </i>
                                                Pasif Yap
                                            </a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-primary btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                                <i class="fas fa-trash">
                                                </i>
                                                Aktif Yap
                                            </a>
                                        }
                                    </td>
                                </tr>

                            }

                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </section>
            <!-- /.content -->
</body>
</html>
<a href="~/Heading/AddHeading/" class="btn btn-dark">Yeni Başlık Ekle</a>

@*<h2>Başlıklar</h2>



    <table class="table table-bordered">
        <tr>
            <th>ID</th>
            <th>BAŞLIK</th>
            <th>KATEGORİ</th>
        </tr>
        @foreach (var x in Model)
                                {
            <tr>
                <td>@x.HeadingID</td>
                <td>@x.HeadingName</td>
                <td>@x.Category.CategoryName</td>
            </tr>
        }
    </table>
    <a href=*@@*"/Heading/AddHeading/" class="btn btn-dark">Yeni Başlık Ekle</a>*@