MvcKutuphane/MvcKutuphane/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;

namespace MvcKutuphane.Controllers
{
    public class PersonelController : Controller
    {
        // GET: Personel
        DBKutuphaneEntities db=new DBKutuphaneEntities();
        public ActionResult Index()
        {
            var degerler = db.TblPersonel.ToList();
            return View(degerler);
        }

        [HttpGet]
        public ActionResult PersonelEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PersonelEkle(TblPersonel p)
        {
            if (!ModelState.IsValid)
            {
                return View("PersonelEkle");
            }
            db.TblPersonel.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelSil(int id)
        {
            var personel = db.TblPersonel.Find(id);
            db.TblPersonel.Remove(personel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelGetir(int id)
        {
            var personel = db.TblPersonel.Find(id);
            return View("PersonelGetir", personel);
        }

        public ActionResult PersonelGuncelle(TblPersonel p)
        {
            var deger = db.TblPersonel.Find(p.ID);
            deger.PERSONEL = p.PERSONEL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/MvcKutuphane/Views/Personel/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TblPersonel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personeller</h2>

<table class="table table-bordered">
<tr>
    <th>PERSONEL ID</th>
    <th>PERSONEL ADI</th>
    <th>SİL</th>
    <th>GÜNCELLE</th>
</tr>
@foreach (var x in Model)
{
    <tr>
        <td>@x.ID</td>
        <td>@x.PERSONEL</td>
        <td>
            @*<a href="/Kategori/KategoriSil/@x.ID" class="btn btn-danger">SİL</a>*@
            <form action="/Personel/PersonelSil/@x.ID">
                <button class="btn btn-danger" id="BtnSil">Sil</button>
            </form>
        </td>
        <td><a href="/Personel/PersonelGetir/@x.ID" class="btn btn-success">GÜNCELLE</a></td>
    </tr>
}
</table>
<a href="/Personel/PersonelEkle/" class="btn btn-primary">Yeni Personel Ekle</a>

MvcKutuphane/MvcKutuphane/Views/Personel/PersonelEkle.cshtml
@model MvcKutuphane.Models.Entity.TblPersonel
@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personel Ekleme Sayfası</h2>

@using (Html.BeginForm("PersonelEkle", "Personel", FormMethod.Post))
{
    @Html.LabelFor(x=>x.PERSONEL)
    @Html.TextBoxFor(x=>x.PERSONEL,new{@class="form-control"})
    @Html.ValidationMessageFor(x=>x.PERSONEL,"",new{@style="color:red;"})
    <br/><br/>
    <button class="btn btn-primary">Personel Ekle</button>
}

MvcKutuphane/MvcKutuphane/Views/Personel/PersonelGetir.cshtml
@model MvcKutuphane.Models.Entity.TblPersonel
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("PersonelGuncelle", "Personel", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.ID)
    @Html.LabelFor(x=>x.PERSONEL)
    @Html.TextBoxFor(x=>x.PERSONEL,new{@class="form-control"})
    <br/>
    <button class="btn btn-primary">Personel Güncelle</button>
}