MVCProjeKampi/MVCProjeKampi/Controllers/AdminCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer;
using FluentValidation.Results;

namespace MVCProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        // GET: AdminCategory
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        [Authorize(Roles = "A")]
        public ActionResult Index()
        {
            var categoryValues = cm.GetList();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            CategoryValidator categoryValidator=new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(category);
            if (results.IsValid)
            {
                cm.CategoryAddBL(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
                }
            }

            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            cm.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryValue = cm.GetByID(id);
            return View(categoryValue);
        }

        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            cm.CategoryUpdate(category);
            return RedirectToAction("Index");
        }
    }
}

MVCProjeKampi/MVCProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddCategory</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <h3>Kategori Ekleme Sayfası</h3>

        @using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
        {
            @Html.Label("Kategori Adı");
            @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" });
            @Html.ValidationMessageFor(x => x.CategoryName);
            <br />
            @Html.Label("Kategori Açıklaması");
            @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" });
            @Html.ValidationMessageFor(x => x.CategoryDescription);
            <br />
            <button class="btn btn-primary" type="submit">Ekle</button>
        }

    </div>
</body>
</html>

MVCProjeKampi/MVCProjeKampi/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategori Güncelleme İşlemleri</h2>

<div class="form-group">
    @using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
    {
        @Html.Label("Kategori ID");
        @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" });
        <br />
        @Html.Label("Kategori Adı");
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" });
        <br />
        @Html.Label("Açıklama");
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" });
        <br />
        <button type="submit" class="btn btn-success">Güncelle</button>
    }





</div>

MVCProjeKampi/MVCProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer
@model List<Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="container">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>KATEGORİ ADI</th>
                <th>AÇIKLAMA</th>
                <th>SİL</th>
                <th>GÜNCELLE</th>
                <th>BAŞLIKLAR</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.CategoryID</td>
                    <td>@item.CategoryName</td>
                    <td>@item.CategoryDescription</td>
                    <td><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">SİL</a></td>
                    <td><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-success">GÜNCELLE</a></td>
                    <td><a href="#" class="btn btn-primary">BAŞLIKLAR</a></td>
                    
                </tr>
            }
        </tbody>
    </table>
    <a href="/AdminCategory/AddCategory/" class="btn btn-dark">Yeni Kategori Ekle</a>
</div>